services:

  db:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 10s
    restart: unless-stopped

  web:
    build:
      context: ./app
      dockerfile: Dockerfile
    image: django-upload-app:1.0
    env_file:
      - .env
    volumes:
      - media_volume:/app/media
      - static_volume:/app/staticfiles
    depends_on:
      db:
        condition: service_healthy
    networks:
      - frontend
      - backend
    restart: unless-stopped

  nginx:
    image: nginx:1.27-alpine
    ports:
      - "8090:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - media_volume:/app/media:ro
      - static_volume:/app/staticfiles:ro
    depends_on:
      - web
    networks:
      - frontend
    restart: unless-stopped

volumes:
  postgres_data:
  media_volume:
  static_volume:

networks:
  frontend:
  backend:
